### ISSUE TITLE
ATÉ QUANDO?

### ISSUE THREAD

**Issue by chmieleski** [devmauromoura/milhoapp#1]
**QUANDO QUE VAI FICAR DISPONÍVEL A URL PUBLICA PARA EU TERMINAR O APLICATIVO?
VAI FICAR ME ENROLANDO ATÉ QUANDO?**
Grrr.

**Comment by devmauromoura** [comment]
Ja te passei no whats, porem a domínio não depende de mim, mas sim de nosso querido coordenador
